# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MR.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MR.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x08MR.proto\"\x9c\x03\n\x08MutexRun\x12\x11\n\tdata_file\x18\x01 \x01(\t\x12\x16\n\x0emax_group_size\x18\x02 \x01(\x05\x12$\n\x1c\x66irst_level_random_iteration\x18\x03 \x01(\x05\x12%\n\x1dsecond_level_random_iteration\x18\x04 \x01(\x05\x12\x12\n\nfdr_cutoff\x18\x05 \x01(\x02\x12\x14\n\x0cscore_cutoff\x18\x06 \x01(\x02\x12#\n\x1bsearch_on_signaling_network\x18\x07 \x01(\x08\x12*\n\"minimum_alteration_count_threshold\x18\x08 \x01(\x05\x12\x12\n\ngene_limit\x18\t \x01(\x05\x12\x12\n\ngenes_file\x18\n \x01(\t\x12\x19\n\x11gene_ranking_file\x18\x0b \x01(\t\x12\x14\n\x0cnetwork_file\x18\x0c \x01(\t\x12%\n\x1dsample_to_tissue_mapping_file\x18\r \x01(\t\x12\x1d\n\x15randomize_data_matrix\x18\x0e \x01(\x08\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MUTEXRUN = _descriptor.Descriptor(
  name='MutexRun',
  full_name='MutexRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data_file', full_name='MutexRun.data_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_group_size', full_name='MutexRun.max_group_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_level_random_iteration', full_name='MutexRun.first_level_random_iteration', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='second_level_random_iteration', full_name='MutexRun.second_level_random_iteration', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fdr_cutoff', full_name='MutexRun.fdr_cutoff', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score_cutoff', full_name='MutexRun.score_cutoff', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='search_on_signaling_network', full_name='MutexRun.search_on_signaling_network', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minimum_alteration_count_threshold', full_name='MutexRun.minimum_alteration_count_threshold', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gene_limit', full_name='MutexRun.gene_limit', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='genes_file', full_name='MutexRun.genes_file', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gene_ranking_file', full_name='MutexRun.gene_ranking_file', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='network_file', full_name='MutexRun.network_file', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_to_tissue_mapping_file', full_name='MutexRun.sample_to_tissue_mapping_file', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='randomize_data_matrix', full_name='MutexRun.randomize_data_matrix', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=425,
)

DESCRIPTOR.message_types_by_name['MutexRun'] = _MUTEXRUN

MutexRun = _reflection.GeneratedProtocolMessageType('MutexRun', (_message.Message,), dict(
  DESCRIPTOR = _MUTEXRUN,
  __module__ = 'MR_pb2'
  # @@protoc_insertion_point(class_scope:MutexRun)
  ))
_sym_db.RegisterMessage(MutexRun)


# @@protoc_insertion_point(module_scope)
